-- Intra-bank transfer pairing.
--
-- When a tenant moves money between two linked accounts the matcher used
-- to see two unmatched transactions: an outflow on account A and an inflow
-- on account B for the same amount. Adding transfer_pair_id lets us mark
-- both rows with a shared id so the UI can render them as one logical
-- movement (and so the mystery-outflow detector knows to skip them).
--
-- The id is generated by the sync-time pairing helper (one UUID per pair),
-- not derived from either row's id. Null means the row is unpaired — every
-- row starts that way; only intra-bank transfers ever get an id.

ALTER TABLE "bank_transactions"
  ADD COLUMN IF NOT EXISTS "transfer_pair_id" uuid;--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "bank_transactions_transfer_pair_idx"
  ON "bank_transactions" USING btree ("transfer_pair_id");
